FROM node:12.18.1

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

# Azure wasn't recognized, couldn't get the secret word :(
ENV SECRET_WORD=searching

RUN npm ci --production

COPY . .

CMD [ "node", "src/000.js" ]